### ISSUE TITLE
Can't get level 0 data for Tanzania

### ISSUE THREAD

**Issue by seor12** [12rambau/pygadm#66]
Tried this 

gdf = pygadm.Items(admin='TZA', content_level=0)

But I get this Exception 

Exception: We cannot retrieve the data from GADM server. Try to manually open the following link: https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_TZA_0.json. If it doesn't work, the error is coming from GADM servers. If it works please open an issue on our repository: https://github.com/12rambau/pygadm/issues.

The link works fine. I have tried other countries, such as AUS, which seem to work fine, just having the issue with Tanzania. Please can someone help?

**Comment by 12rambau** [comment]
I just tried on my local computer and it works as expected: 

<img width="960" alt="image" src="https://github.com/12rambau/pygadm/assets/12596392/057e07af-1cc4-4785-9ca1-acf6c97c4f88">

Can you retry from your side and make sure you are using the latest version of the software ?

**Comment by 12rambau** [comment]
I checked again this morning and it still works. Happy to have a look again if you can reproduce your bug.
