### ISSUE TITLE
Unable to load Items by name

### ISSUE THREAD

**Issue by leoduret** [12rambau/pygadm#68]
**Describe the bug**

`Names` returns the right admin code but no geometries are returned using `Items`

**To Reproduce**

Pass `United States`, `South Africa` by name to Items no geometries are returned.
Will return geometries only by admin so `USA` and `ZAF`

**Screenshots**
![image](https://github.com/12rambau/pygadm/assets/148475860/4c7b8939-1bcc-413e-98b9-44ed4e8cf780)

**Comment by leoduret** [comment]
Saudi Arabia is also missing

**Comment by 12rambau** [comment]
- [ ] "Pakistan": "PAK",
- [ ] "India": "IND",
- [ ] "China": "CHN",
- [ ] "United States": "USA",
- [ ] "South Africa": "ZAF",
- [ ] "Saudi Arabia": "SAU",
- [ ] "Democratic republic of the congo": "COD",
- [ ] "United Kingdom": "GBR",
- [ ] "New Zealand": "NZL",
- [ ] "Papua New Guinea": "PNG",
- [ ] "Mexico": "MEX",
- [ ] "Costa Rica": "CRI",
- [ ] "Dominican Republic": "DOM",
- [ ] "Sierra Leone": "SLE",
- [ ] "Côte d'Ivoire": "CIV",
- [ ] "Burkina Faso": "BFA",
- [ ] "Equatorial Guinea": "GNQ",
- [ ] "Central African Republic": "CAF",
- [ ] "South Sudan": "SSD",
- [ ] "Republic of the Congo": "COG",
- [ ] "South Korea": "KOR",

**Comment by 12rambau** [comment]
I think the PR will close this issue. The remaining ones are conflicting as the name exist in multiple places on the planet. let's use another issue to add this feature.
